### ISSUE TITLE
add LocalValue tests

### ISSUE THREAD

**Issue by fes300** [fido-id/localvalue-ts#1]
all helper functions in LocalValue.ts should be tested

**Comment by ranpafin** [comment]
Unit testing:

- [ ] fold
- [ ] fold2
- [ ] getOrElse
- [ ] getOrElseW
- [ ] of
- [ ] chain
- [ ] map
- [ ] fromOption
- [ ] fromEither
- [ ] toOption
- [ ] toEither
- [ ] alt
- [ ] isAbsent
- [ ] isValid
- [ ] isInvalid
- [ ] absent
